version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: decorator
    versions:
    - 4.4.2
    - 5.0.0
    - 5.0.5
    - 5.0.6
  - dependency-name: terminado
    versions:
    - 0.9.2
    - 0.9.3
  - dependency-name: pygments
    versions:
    - 2.7.4
    - 2.8.0
  - dependency-name: urllib3
    versions:
    - 1.26.3
  - dependency-name: nbformat
    versions:
    - 5.1.2
  - dependency-name: pytz
    versions:
    - "2020.5"
  - dependency-name: more-itertools
    versions:
    - 8.6.0
